#!/usr/bin/env python

import rospy
from std_msgs.msg import Float32

def talker():
    pub = rospy.Publisher('gps',Float32, queue_size=10)
    rospy.init_node('gps_node', anonymous=True)
    rate = rospy.Rate(10) # 10hz
    while not rospy.is_shutdown():
        value = 10
        rospy.loginfo("Publish")
        pub.publish(value)
        rate.sleep()

# if __name__ == '__main__':
#     try:
#         talker()
#     except rospy.ROSInterruptException:
#         pass

if __name__ == '__main__':
    talker()