#!/usr/bin/env python3

import rospy
from std_msgs.msg import Float32
from axotec.gps import GPS  


gps = GPS()
def talker():
    
    pub = rospy.Publisher('gps_speed',Float32, queue_size=10)
    rospy.init_node('gps_node', anonymous=True)
    rate = rospy.Rate(10) # 10hz
    while not rospy.is_shutdown():
        gps_speed = gps.get_vel()
        if gps_speed is not None:
            rospy.loginfo(gps_speed)
            pub.publish(gps_speed)
            rate.sleep()    

# if __name__ == '__main__':
#     try:
#         talker()
#     except rospy.ROSInterruptException:
#         pass

if __name__ == '__main__':
    talker()