#!/usr/bin/env python3

import rospy
import paho.mqtt.client as mqtt
from std_msgs.msg import Float32

USERNAME = 'AxotecPiloto'
PASSWORD = '1234567890'

# Server de ACME
MQTT_SERVER = 'soldier.cloudmqtt.com'
MQTT_PORT = 15258


class MqttSender:
    def __init__(self):
        self.dt = 0.5
        self.filtered_speed = 0
        self.gps_speed = 0
        self.obd2_speed = 0
        # Subscriptores a los tópicos de interes
        rospy.Subscriber("/gps_speed", Float32, self.gps_callback)
        rospy.Subscriber("/speed_filtered", Float32, self.filter_callback) 
        rospy.Subscriber("/obd2_speed", Float32, self.obd2_callback)  

        # mqtt
        self.client = mqtt.Client()  
        self.client.username_pw_set(USERNAME, PASSWORD)
        self.client.connect(MQTT_SERVER, MQTT_PORT,60)
        self.client.loop_start()


    def gps_callback(self, data):
        self.gps_speed = data.data

    def filter_callback(self, data):
        self.filtered_speed = data.data

    def obd2_callback(self, data):
        self.obd2_speed = data.data
        

    def run(self):
        # Bucle principal
        while not rospy.is_shutdown():
            # Espera para mantener la frecuencia de muestreo
            # Publicamos al broker cada 0.5 s
            self.client.publish("/gps_speed", self.gps_speed)
            self.client.publish("/speed_filtered", self.filtered_speed)
            self.client.publish("/obd2_speed", self.obd2_speed)
            self.client.loop()
            rospy.sleep(self.dt)

if __name__ == '__main__':
    # Inicializa el nodo ROS
    rospy.init_node('mqtt_sender')

    # Crea un objeto ComplementaryFilter
    ms = MqttSender()

    # Ejecuta el filtro complementario
    ms.run()

    # Para la ejecución del nodo ROS
    rospy.spin()