#!/usr/bin/env python3

import rospy
from std_msgs.msg import Float32




def on_gps(data):
    rospy.loginfo(f"GPS speed: {data.data}")

def on_imu(data):
    rospy.loginfo(f"IMU speed: {data.data}")

def main():

    # In ROS, nodes are uniquely named. If two nodes with the same
    # name are launched, the previous one is kicked off. The
    # anonymous=True flag means that rospy will choose a unique
    # name for our 'listener' node so that multiple listeners can
    # run simultaneously.
    rospy.init_node('speed_filter', anonymous=True)

    rospy.Subscriber('/gps_speed', Float32, on_gps)
    rospy.Subscriber('/imu_speed', Float32, on_imu)

    # spin() simply keeps python from exiting until this node is stopped
    rospy.spin()

if __name__ == '__main__':
    main()
